"""`feinschliff-builder slotify …` — slotify every decompiled layout in a
brand pack: literal text labels → `{{ text_N | default("literal") }}` slots,
so the pack works as a fillable template while the bare showcase render
stays identical (defaults).

Also auto-generates layout-picker frontmatter (role / ideal_count /
data_band / comparison + slot roles + image queries — see
`feinschliff_builder.decompile.layout_profile_gen`) and writes
`deck-map.yaml` mapping deck roles to layouts. Without the frontmatter,
`build_profile_table(strict=False)` silently drops decompiled layouts
and the /deck picker can never choose them. Skip with `--no-profiles`.

Step 2 of brand bootstrap — run after `decompile`.

→ Canonical pipeline: see `feinschliff-builder/README.md`.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

from feinschliff_builder.decompile.cleanup import native_pic_rects, strip_native_text_doubles
from feinschliff_builder.decompile.layout_profile_gen import (
    apply_profile,
    classify_layout,
    derive_deck_map,
)
from feinschliff_builder.decompile.slotify import (
    add_autoshrink,
    autoshrink_enabled,
    clip_text_to_images,
    clip_to_images_enabled,
    slotify_dsl,
    slotify_native_text,
)
from feinschliff_builder.verify.verify_map import load_verify_map

_DECK_MAP_HEADER = (
    "# Auto-generated by `feinschliff-builder slotify` — layout roles for deck planning.\n"
)


def _slide_indices(brand_pack: Path, names: list[str]) -> tuple[dict[str, int], int]:
    """Layout name → 1-based slide index. Prefers the brand's verify-map.yaml
    (`layouts:` mapping, the decompile source-slide order); falls back to the
    sorted-filename enumeration for unmapped names / mapless brands."""
    verify_map: dict[str, int] = {}
    try:
        verify_map = dict(load_verify_map(brand_pack).layouts)
    except FileNotFoundError:
        pass  # brand has no verify-map.yaml; fall back to filename enumeration
    except ValueError:
        pass  # malformed map; fall back gracefully
    indices = {
        name: verify_map.get(name, pos + 1) for pos, name in enumerate(names)
    }
    total = max(indices.values(), default=0)
    return indices, total


def _apply_deck_map_pins(brand_pack: Path, deck_map: dict) -> tuple[dict, bool]:
    """Merge `<brand-pack>/deck-map.pins.yaml` over the generated deck-map.

    Pins survive every regeneration: scalar roles (cover/agenda/closer)
    override, a pinned `section:` list replaces the generated one, and all
    pinned layouts are removed from `content`. Returns (map, pinned?)."""
    pins_path = brand_pack / "deck-map.pins.yaml"
    if not pins_path.is_file():
        return deck_map, False
    pins = yaml.safe_load(pins_path.read_text(encoding="utf-8")) or {}
    for key in ("cover", "agenda", "closer"):
        if pins.get(key):
            deck_map[key] = pins[key]
    if pins.get("section"):
        deck_map["section"] = list(pins["section"])
    pinned = {deck_map.get("cover"), deck_map.get("agenda"), deck_map.get("closer"),
              *(deck_map.get("section") or [])}
    deck_map["content"] = [x for x in (deck_map.get("content") or [])
                           if x not in pinned]
    return deck_map, True


def _pack_width_emu(brand_pack: Path) -> float:
    """slide.width_emu from tokens.json (0.0 when absent — geometry check
    in strip_native_text_doubles then falls back to literal-only match)."""
    try:
        raw = json.loads((brand_pack / "tokens.json").read_text(encoding="utf-8"))
        return float(raw["slide"]["width_emu"]["$value"])
    except Exception:
        return 0.0


def register(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--brand-pack", required=True, type=Path)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--no-profiles", action="store_true",
                        help="skip frontmatter profile + deck-map generation")
    parser.set_defaults(func=cmd_slotify)


def cmd_slotify(args) -> int:
    brand_pack = args.brand_pack.resolve()
    layouts_dir = brand_pack / "layouts"
    if not layouts_dir.is_dir():
        print(f"slotify: no layouts/ in {args.brand_pack}", file=sys.stderr)
        return 2

    clip_enabled = clip_to_images_enabled(brand_pack)
    total_slots = 0
    unslotified_text = 0
    unslotified_pics = 0
    slotified: dict[str, str] = {}  # layout name → slotified DSL text
    clip_log: dict[str, list[str]] = {}  # layout name → clip log lines
    for path in sorted(layouts_dir.glob("*.slide.dsl")):
        text = path.read_text(encoding="utf-8")
        new_text, slots = slotify_dsl(text)
        if not args.dry_run:
            # Native runs that double a regular text line's label render
            # stacked once a deck binds either copy — blank the native run
            # (the text slot is the single binding point), THEN slotify the
            # remaining native payload text. Sidecar payloads rewrite on
            # disk, so both passes are skipped on dry runs.
            new_text, doubles = strip_native_text_doubles(
                new_text, brand_pack / "assets",
                width_emu=_pack_width_emu(brand_pack))
            if doubles:
                print(f"  {path.name}: blanked {doubles} native text double(s)")
            new_text, native_slots, native_logs = slotify_native_text(
                new_text, brand_pack / "assets")
            for line in native_logs:
                print(f"  {path.name}: {line}")
            slots = slots + [ns["name"] for ns in native_slots]
        if clip_enabled:
            new_text, clips = clip_text_to_images(
                new_text,
                extra_images=native_pic_rects(
                    new_text, brand_pack / "assets",
                    width_emu=_pack_width_emu(brand_pack)))
            if clips:
                clip_log[path.name[: -len(".slide.dsl")]] = clips
        leftovers = [ln for ln in new_text.splitlines()
                     if ln.startswith("text ") and '"' in ln and "{{" not in ln]
        bare_pics = [ln for ln in new_text.splitlines()
                     if ln.startswith("picture ") and "{{" not in ln]
        unslotified_text += len(leftovers)
        unslotified_pics += len(bare_pics)
        total_slots += len(slots)
        flag = ""
        if leftovers:
            flag += f"  [{len(leftovers)} text left literal]"
        if bare_pics:
            flag += f"  [{len(bare_pics)} picture without slot]"
        print(f"  {path.name}: {len(slots)} text slots{flag}")
        if not args.dry_run and new_text != text:
            path.write_text(new_text, encoding="utf-8")
        slotified[path.name[: -len(".slide.dsl")]] = new_text

    mode = "(dry-run) " if args.dry_run else ""
    print(f"\n{mode}{total_slots} text slots across "
          f"{len(list(layouts_dir.glob('*.slide.dsl')))} layouts; "
          f"{unslotified_text} text lines left literal, "
          f"{unslotified_pics} pictures without slot")
    if clip_log:
        total_clips = sum(len(v) for v in clip_log.values())
        print(f"text-over-image clips: {total_clips} across {len(clip_log)} layout(s):")
        for name in sorted(clip_log):
            for msg in clip_log[name]:
                print(f"  {name}: {msg}")

    if not args.no_profiles and slotified:
        names = sorted(slotified)
        indices, total = _slide_indices(brand_pack, names)
        profiles: dict[str, dict] = {}
        for name in names:
            profile = classify_layout(
                slotified[name],
                layout_name=name,
                slide_index=indices[name],
                total_slides=total,
                asset_root=brand_pack / "assets",
                brand_dir=brand_pack,
            )
            profiles[name] = profile
            roles = {n: meta.get("role", "")
                     for n, meta in (profile.get("slots") or {}).items()}
            if autoshrink_enabled(brand_pack):
                slotified[name] = add_autoshrink(slotified[name], roles)
            # Recompute source_hash AFTER every body-modifying pass
            # (add_autoshrink etc.) so the recorded fingerprint matches
            # the body actually written. classify_layout's initial hash
            # is of the pre-autoshrink body — overwrite it here. lstrip()
            # so split_frontmatter's line-preservation padding doesn't
            # make the hash sensitive to fence size.
            import hashlib as _hashlib
            from feinschliff_builder.decompile.layout_profile_gen import split_frontmatter as _split
            _, _final_body = _split(slotified[name])
            profile["source_hash"] = _hashlib.sha1(
                _final_body.strip().encode("utf-8")).hexdigest()[:12]
            if not args.dry_run:
                path = layouts_dir / f"{name}.slide.dsl"
                path.write_text(apply_profile(slotified[name], profile),
                                encoding="utf-8")
        flagged = {n: p["slot_warnings"] for n, p in profiles.items()
                   if p.get("slot_warnings")}
        if flagged:
            total_warnings = sum(
                len(msgs) for w in flagged.values() for msgs in w.values()
            )
            print(f"slot-warnings: {total_warnings} across {len(flagged)} layout(s):")
            for name in sorted(flagged):
                for slot, msgs in sorted(flagged[name].items()):
                    for msg in msgs:
                        print(f"  {name}.{slot}: {msg}")
        deck_map = derive_deck_map(profiles)
        deck_map, pinned = _apply_deck_map_pins(brand_pack, deck_map)
        if not args.dry_run:
            header = _DECK_MAP_HEADER
            if pinned:
                header += ("# Roles merged from deck-map.pins.yaml — edit pins "
                           "there, they survive regeneration.\n")
            (brand_pack / "deck-map.yaml").write_text(
                header + yaml.safe_dump(
                    deck_map, sort_keys=False, allow_unicode=True,
                    default_flow_style=None),
                encoding="utf-8")
        role_counts: dict[str, int] = {}
        for profile in profiles.values():
            role_counts[profile["role"]] = role_counts.get(profile["role"], 0) + 1
        roles = ", ".join(f"{r} {n}" for r, n in sorted(
            role_counts.items(), key=lambda kv: (-kv[1], kv[0])))
        print(f"{mode}profiles: {len(profiles)} layouts, roles: {roles}, "
              f"deck-map {'skipped' if args.dry_run else 'written'}")
    return 0
